---
title: "midterm project team 5"
output: html_document
date: "2022-10-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

install some packages or libraries
```{r}

library(ggplot2)
library(ezids)
library(dplyr)
library(readr)
```

## read data
Read the data .CSV files of adults arrest in DC area from 2016-2021
```{r }

df_2016<-data.frame(read.csv("Arrests 2016 Public.csv"))
df_2017<-data.frame(read.csv("Arrests 2017 Public.csv"))
df_2018<-data.frame(read.csv("Arrests by Year, 2018.csv"))
df_2019<-data.frame(read.csv("Arrests by Year, 2019.csv"))
df_2020<-data.frame(read.csv("Arrests by Year 2020.csv"))
df_2021<-data.frame(read.csv("2021 Adult Arrests.csv"))
```

###Some data cleaning.. Dropping, Binding and Renaming of columns as needed.
```{r}
#bind the rows in the dataframes; 
# data for year 2016 & 2017 have different column listings to the rest of the dataframes..

colnames(df_2016) = colnames(df_2017)
df_16_17 = rbind(df_2016,df_2017)

#also remove certain hard-coded columns that are not really needed in this analysis (leaving district location for now)
df_16_17 = df_16_17[-c(5,6,15,17:21,23:26)]
df_16_17 <- df_16_17 %>% 
       rename("Offense.Location.District" = "Offense.District")

# replace dots with underscore for clarity sake, i think..
names(df_16_17) = gsub("[.]", "_", names(df_16_17))
colnames(df_16_17)
```

```{r}
# since col names in 2018-2021 are the same, we repeat same processes as above.
df_18_21 = rbind(df_2018,df_2019,df_2020,df_2021)[,-c(5,6,15,17:21,23:26)]

# replace dots with underscore once more
names(df_18_21) = gsub("[.]", "_", names(df_18_21))
colnames(df_18_21)
```

```{r}
#Now bind both newly created dataframes into 1 whole table.
df_full = rbind(df_16_17,df_18_21)
#check for column names
colnames(df_full)
```

```{r}
#find unique values in the race, sex and arrest_category columns.
#unique(df_full$Defendant_Race)
#unique(df_full$Defendant_Sex)
#unique(df_full$Arrest_Category)

# most likely "UNK" is the same as "Unknown", so we can change this
df_full$Defendant_Race[df_full$Defendant_Race == 'UNK'] <- 'UNKNOWN'
#unique(df_full$Defendant_Race) - check that it changed

#same issue, "unk" is very likely "unknown", so change it.
df_full$Defendant_Sex[df_full$Defendant_Sex == 'UNK'] <- 'UNKNOWN'
#unique(df_full$Defendant_Sex) - check that it changed

# Arrest category -  4 different types of Fraud & Financial crimes , 3 types of Release Violations/Fugitive -- group them into one.

df_full$Arrest_Category = gsub("Fraud and Financial Crimes.*","Fraud and Financial Crimes", df_full$Arrest_Category)

df_full$Arrest_Category = gsub("Release Violations/Fugitive.*","Release Violations/Fugitive",df_full$Arrest_Category)

#sort(unique(df_full$Arrest_Category)) - check that new changes were made.
```




## Including Plots



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


